from commons.py

exception_handler: not called
build_failure_reply: not called

makes sense because there weren't any errors